/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myapp;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omar
 */
public class TableData extends javax.swing.JPanel {

    /**
     * Creates new form TableData
     */
    public TableData() {
        initComponents();
    }

    public TableData(String[] headers, Object[][] rowData) {
        initComponents();
        loadData(headers, rowData);
        detailedCellInfo();
    }

    private void loadData(String[] headers, Object[][] rowData) {
        // Get the current table model
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Clear any existing rows in the table
        model.setRowCount(0);

        // Set column headers dynamically based on the input
        setTableHeaders(headers);

        // Add row data dynamically based on the input
        for (Object[] row : rowData) {
            model.addRow(row);
        }
    }

    private void detailedCellInfo() {
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = jTable1.rowAtPoint(e.getPoint());
                int column = jTable1.columnAtPoint(e.getPoint());

                // Make sure the clicked cell is valid
                if (row >= 0 && column >= 0) {
                    Object cellValue = jTable1.getValueAt(row, column);
                    String message = "Cell Details:\n"
                            + "Row: " + (row + 1) + "\n"
                            + "Column: " + jTable1.getColumnName(column) + "\n"
                            + "Value: " + cellValue;

                    // Displaying the details in a dialog box
                    JOptionPane.showMessageDialog(null, message, "Cell Details", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
    }

    private void setTableHeaders(String... headers) {
        // Get the current table model
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Set the column names dynamically based on the input
        model.setColumnIdentifiers(headers);
    }

    private int mapDayToColumn(String day) {
        switch (day) {
            case "Monday":
                return 2;
            case "Tuesday":
                return 3;
            case "Wednesday":
                return 4;
            case "Thursday":
                return 5;
            case "Friday":
                return 6;
            case "Saturday":
                return 7;
            default:
                return -1; // Invalid day
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
